HOMEPAGE = "https://www.lounaat.info/"
BROWSER = "Chrome"
ID_CONTENT = "//*[@id=\"content\"]/div/div[1]/div/div/section[2]/div/div/div[1]/div/div/div[9]"
PATH_FILE_WITH_NAMES = "${CURDIR}/../file_resources/restaurant_list.txt"
PATH_FILE_TO_WRITE = "${CURDIR}/../file_resources/menus_list.txt"